### ISSUE TITLE
Add image to img/privly with file name - nitin 

### ISSUE THREAD

**Issue by nitin10s** [fossasia/gci15.fossasia.org#728] opened 2016-02-03 17:15 UTC
![final2](https://cloud.githubusercontent.com/assets/16988558/12790335/cd806866-cac7-11e5-935a-6adbc7a7cc10.png)

**Comment by sumsupee** [comment] 2016-02-04 03:03
@nitin10s You haven't elaborated what the issue is!

**Comment by abishekvashok** [comment] 2016-02-04 11:21
@nitin10s please close this issue, it's never an issue if you added a sticker

**Comment by nitin10s** [comment] 2016-02-05 12:32
No actually i am new to github and coding so can you guys help me the way to add my stickers to img/privly section

**Comment by sumsupee** [comment] 2016-02-05 16:33
@nitin10s Hello, you don't have to do much, but just edit the following details of the code present in the angle brackets and add it to index.html file.

I hope you have already added your stickers to the `img/privly` in the .PNG format.

```
<div class="thumbnail folio-thumb">
  <figure class="gallery-item">
        <img alt="Sticker" src="img/privly/<your_sticker_name>.PNG" 
            <figcaption class="img-title">
                <h4><your header>
                    <a href="https://github.com/<your GitHub handle>">
                       <i id="github" class="icon-github">
                       </i>
                    </a>
                 </h4>
           </figcaption>
        </figure>
     <h3>Made by ....</h3>
 </div>
```

If you have anymore problems with Github, have a look at [GIT.md](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md)

And if you've further problems you must consider re-learning Git or asking for more help.

**P.S.** Please mention the github account of the person you want to contact. You must use the @ symbol for this, like I've done to mention you in the comment at the beginning. When you mention a person using the @ symbol, the person you mention gets a notification, but when you don't mention anybody, nobody receives a notification to the message and are unaware of the progress. I came back to this issue as I saw that this issue was still not closed. This is helpful for learning [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

**Comment by abishekvashok** [comment] 2017-05-23 10:04
@jig08 this one too #722

**Closed as completed** 2017-05-23 10:26 UTC
